//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CognitiveLocator.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CognitiveLocator.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        public static string Login_Proceed {
            get {
                return ResourceManager.GetString("Login_Proceed", resourceCulture);
            }
        }
        
        public static string Login_Login {
            get {
                return ResourceManager.GetString("Login_Login", resourceCulture);
            }
        }
        
        public static string Catalogs_LanguageSpanish {
            get {
                return ResourceManager.GetString("Catalogs_LanguageSpanish", resourceCulture);
            }
        }
        
        public static string Catalogs_LanguageEnglish {
            get {
                return ResourceManager.GetString("Catalogs_LanguageEnglish", resourceCulture);
            }
        }
        
        public static string Catalogs_GenreMale {
            get {
                return ResourceManager.GetString("Catalogs_GenreMale", resourceCulture);
            }
        }
        
        public static string Catalogs_GenreFemale {
            get {
                return ResourceManager.GetString("Catalogs_GenreFemale", resourceCulture);
            }
        }
        
        public static string CreateReport_Title {
            get {
                return ResourceManager.GetString("CreateReport_Title", resourceCulture);
            }
        }
        
        public static string CreateReport_CameraText {
            get {
                return ResourceManager.GetString("CreateReport_CameraText", resourceCulture);
            }
        }
        
        public static string CreateReport_GalleryText {
            get {
                return ResourceManager.GetString("CreateReport_GalleryText", resourceCulture);
            }
        }
        
        public static string CreateReport_DisclaimerHeader {
            get {
                return ResourceManager.GetString("CreateReport_DisclaimerHeader", resourceCulture);
            }
        }
        
        public static string CreateReport_DisclaimerMessage {
            get {
                return ResourceManager.GetString("CreateReport_DisclaimerMessage", resourceCulture);
            }
        }
        
        public static string CreateReport_DisclaimerYes {
            get {
                return ResourceManager.GetString("CreateReport_DisclaimerYes", resourceCulture);
            }
        }
        
        public static string CreateReport_DisclaimerNo {
            get {
                return ResourceManager.GetString("CreateReport_DisclaimerNo", resourceCulture);
            }
        }
        
        public static string CreateReport_ConnectivityHeader {
            get {
                return ResourceManager.GetString("CreateReport_ConnectivityHeader", resourceCulture);
            }
        }
        
        public static string CreateReport_ConnectivityMessage {
            get {
                return ResourceManager.GetString("CreateReport_ConnectivityMessage", resourceCulture);
            }
        }
        
        public static string CreateReport_ConnectivityAccept {
            get {
                return ResourceManager.GetString("CreateReport_ConnectivityAccept", resourceCulture);
            }
        }
        
        public static string CreateReport_InformationNotAvailable {
            get {
                return ResourceManager.GetString("CreateReport_InformationNotAvailable", resourceCulture);
            }
        }
        
        public static string CreateReport_ReportErrorHeader {
            get {
                return ResourceManager.GetString("CreateReport_ReportErrorHeader", resourceCulture);
            }
        }
        
        public static string CreateReport_ReportErrorMessage {
            get {
                return ResourceManager.GetString("CreateReport_ReportErrorMessage", resourceCulture);
            }
        }
        
        public static string CreateReport_ReportErrorAccept {
            get {
                return ResourceManager.GetString("CreateReport_ReportErrorAccept", resourceCulture);
            }
        }
        
        public static string CreateReport_ValidationErrorHeader {
            get {
                return ResourceManager.GetString("CreateReport_ValidationErrorHeader", resourceCulture);
            }
        }
        
        public static string CreateReport_ValidationErrorMessage {
            get {
                return ResourceManager.GetString("CreateReport_ValidationErrorMessage", resourceCulture);
            }
        }
        
        public static string CreateReport_ValidationErrorAccept {
            get {
                return ResourceManager.GetString("CreateReport_ValidationErrorAccept", resourceCulture);
            }
        }
        
        public static string CreateReport_SectionPhoto {
            get {
                return ResourceManager.GetString("CreateReport_SectionPhoto", resourceCulture);
            }
        }
        
        public static string CreateReport_SectionPhotoMessage {
            get {
                return ResourceManager.GetString("CreateReport_SectionPhotoMessage", resourceCulture);
            }
        }
        
        public static string CreateReport_SectionGeneral {
            get {
                return ResourceManager.GetString("CreateReport_SectionGeneral", resourceCulture);
            }
        }
        
        public static string CreateReport_Country {
            get {
                return ResourceManager.GetString("CreateReport_Country", resourceCulture);
            }
        }
        
        public static string CreateReport_ReportedBy {
            get {
                return ResourceManager.GetString("CreateReport_ReportedBy", resourceCulture);
            }
        }
        
        public static string CreateReport_Name {
            get {
                return ResourceManager.GetString("CreateReport_Name", resourceCulture);
            }
        }
        
        public static string CreateReport_Lastname {
            get {
                return ResourceManager.GetString("CreateReport_Lastname", resourceCulture);
            }
        }
        
        public static string CreateReport_LocationOfLoss {
            get {
                return ResourceManager.GetString("CreateReport_LocationOfLoss", resourceCulture);
            }
        }
        
        public static string CreateReport_DateOfLoss {
            get {
                return ResourceManager.GetString("CreateReport_DateOfLoss", resourceCulture);
            }
        }
        
        public static string CreateReport_ReportId {
            get {
                return ResourceManager.GetString("CreateReport_ReportId", resourceCulture);
            }
        }
        
        public static string CreateReport_PhysicalAttributes {
            get {
                return ResourceManager.GetString("CreateReport_PhysicalAttributes", resourceCulture);
            }
        }
        
        public static string CreateReport_Genre {
            get {
                return ResourceManager.GetString("CreateReport_Genre", resourceCulture);
            }
        }
        
        public static string CreateReport_Complexion {
            get {
                return ResourceManager.GetString("CreateReport_Complexion", resourceCulture);
            }
        }
        
        public static string CreateReport_Skin {
            get {
                return ResourceManager.GetString("CreateReport_Skin", resourceCulture);
            }
        }
        
        public static string CreateReport_Front {
            get {
                return ResourceManager.GetString("CreateReport_Front", resourceCulture);
            }
        }
        
        public static string CreateReport_Mouth {
            get {
                return ResourceManager.GetString("CreateReport_Mouth", resourceCulture);
            }
        }
        
        public static string CreateReport_Eyebrows {
            get {
                return ResourceManager.GetString("CreateReport_Eyebrows", resourceCulture);
            }
        }
        
        public static string CreateReport_Age {
            get {
                return ResourceManager.GetString("CreateReport_Age", resourceCulture);
            }
        }
        
        public static string CreateReport_Height {
            get {
                return ResourceManager.GetString("CreateReport_Height", resourceCulture);
            }
        }
        
        public static string CreateReport_Face {
            get {
                return ResourceManager.GetString("CreateReport_Face", resourceCulture);
            }
        }
        
        public static string CreateReport_Nose {
            get {
                return ResourceManager.GetString("CreateReport_Nose", resourceCulture);
            }
        }
        
        public static string CreateReport_Lips {
            get {
                return ResourceManager.GetString("CreateReport_Lips", resourceCulture);
            }
        }
        
        public static string CreateReport_Chin {
            get {
                return ResourceManager.GetString("CreateReport_Chin", resourceCulture);
            }
        }
        
        public static string CreateReport_TypeColorEyes {
            get {
                return ResourceManager.GetString("CreateReport_TypeColorEyes", resourceCulture);
            }
        }
        
        public static string CreateReport_TypeColorHair {
            get {
                return ResourceManager.GetString("CreateReport_TypeColorHair", resourceCulture);
            }
        }
        
        public static string CreateReport_SectionAditionalInformation {
            get {
                return ResourceManager.GetString("CreateReport_SectionAditionalInformation", resourceCulture);
            }
        }
        
        public static string CreateReport_ParticularSigns {
            get {
                return ResourceManager.GetString("CreateReport_ParticularSigns", resourceCulture);
            }
        }
        
        public static string CreateReport_Clothes {
            get {
                return ResourceManager.GetString("CreateReport_Clothes", resourceCulture);
            }
        }
        
        public static string CreateReport_Next {
            get {
                return ResourceManager.GetString("CreateReport_Next", resourceCulture);
            }
        }
        
        public static string CreateReport_PreviewMessage {
            get {
                return ResourceManager.GetString("CreateReport_PreviewMessage", resourceCulture);
            }
        }
        
        public static string CreateReport_SendReport {
            get {
                return ResourceManager.GetString("CreateReport_SendReport", resourceCulture);
            }
        }
        
        public static string CreateReportConfirmation_Title {
            get {
                return ResourceManager.GetString("CreateReportConfirmation_Title", resourceCulture);
            }
        }
        
        public static string CreateReportConfirmation_P1 {
            get {
                return ResourceManager.GetString("CreateReportConfirmation_P1", resourceCulture);
            }
        }
        
        public static string CreateReportConfirmation_P2 {
            get {
                return ResourceManager.GetString("CreateReportConfirmation_P2", resourceCulture);
            }
        }
        
        public static string CreateReportConfirmation_ButtonHome {
            get {
                return ResourceManager.GetString("CreateReportConfirmation_ButtonHome", resourceCulture);
            }
        }
        
        public static string SearchPerson_Title {
            get {
                return ResourceManager.GetString("SearchPerson_Title", resourceCulture);
            }
        }
        
        public static string SearchPerson_ValidationHeader {
            get {
                return ResourceManager.GetString("SearchPerson_ValidationHeader", resourceCulture);
            }
        }
        
        public static string SearchPerson_ValidationMessage {
            get {
                return ResourceManager.GetString("SearchPerson_ValidationMessage", resourceCulture);
            }
        }
        
        public static string SearchPerson_ValidationAccept {
            get {
                return ResourceManager.GetString("SearchPerson_ValidationAccept", resourceCulture);
            }
        }
        
        public static string SearchPerson_SectionPhoto {
            get {
                return ResourceManager.GetString("SearchPerson_SectionPhoto", resourceCulture);
            }
        }
        
        public static string SearchPerson_SectionPhotoMessage {
            get {
                return ResourceManager.GetString("SearchPerson_SectionPhotoMessage", resourceCulture);
            }
        }
        
        public static string SearchPerson_CameraText {
            get {
                return ResourceManager.GetString("SearchPerson_CameraText", resourceCulture);
            }
        }
        
        public static string SearchPerson_GalleryText {
            get {
                return ResourceManager.GetString("SearchPerson_GalleryText", resourceCulture);
            }
        }
        
        public static string SearchPerson_SearchText {
            get {
                return ResourceManager.GetString("SearchPerson_SearchText", resourceCulture);
            }
        }
        
        public static string SearchPerson_SectionPersonData {
            get {
                return ResourceManager.GetString("SearchPerson_SectionPersonData", resourceCulture);
            }
        }
        
        public static string SearchPerson_Name {
            get {
                return ResourceManager.GetString("SearchPerson_Name", resourceCulture);
            }
        }
        
        public static string SearchPerson_Lastname {
            get {
                return ResourceManager.GetString("SearchPerson_Lastname", resourceCulture);
            }
        }
        
        public static string SearchPersonResult_Title {
            get {
                return ResourceManager.GetString("SearchPersonResult_Title", resourceCulture);
            }
        }
        
        public static string SearchPersonResult_ConnectivityHeader {
            get {
                return ResourceManager.GetString("SearchPersonResult_ConnectivityHeader", resourceCulture);
            }
        }
        
        public static string SearchPersonResult_ConnectivityMessage {
            get {
                return ResourceManager.GetString("SearchPersonResult_ConnectivityMessage", resourceCulture);
            }
        }
        
        public static string SearchPersonResult_ConnectivityAccept {
            get {
                return ResourceManager.GetString("SearchPersonResult_ConnectivityAccept", resourceCulture);
            }
        }
        
        public static string SearchPersonResult_NoResultsHeader {
            get {
                return ResourceManager.GetString("SearchPersonResult_NoResultsHeader", resourceCulture);
            }
        }
        
        public static string SearchPersonResult_NoResultsMessage {
            get {
                return ResourceManager.GetString("SearchPersonResult_NoResultsMessage", resourceCulture);
            }
        }
        
        public static string SearchPersonResult_NoResultsAccept {
            get {
                return ResourceManager.GetString("SearchPersonResult_NoResultsAccept", resourceCulture);
            }
        }
        
        public static string SearchPersonResult_VerificationErrorHeader {
            get {
                return ResourceManager.GetString("SearchPersonResult_VerificationErrorHeader", resourceCulture);
            }
        }
        
        public static string SearchPersonResult_VerificationErrorMessage {
            get {
                return ResourceManager.GetString("SearchPersonResult_VerificationErrorMessage", resourceCulture);
            }
        }
        
        public static string SearchPersonResult_VerificationErrorAccept {
            get {
                return ResourceManager.GetString("SearchPersonResult_VerificationErrorAccept", resourceCulture);
            }
        }
        
        public static string PersonDetail_Title {
            get {
                return ResourceManager.GetString("PersonDetail_Title", resourceCulture);
            }
        }
        
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        public static string Settings_GeneralSettings {
            get {
                return ResourceManager.GetString("Settings_GeneralSettings", resourceCulture);
            }
        }
        
        public static string Settings_LanguageTitle {
            get {
                return ResourceManager.GetString("Settings_LanguageTitle", resourceCulture);
            }
        }
        
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        public static string Settings_LanguageSelect {
            get {
                return ResourceManager.GetString("Settings_LanguageSelect", resourceCulture);
            }
        }
        
        public static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        public static string Home_ReportPerson {
            get {
                return ResourceManager.GetString("Home_ReportPerson", resourceCulture);
            }
        }
        
        public static string Home_NameSearch {
            get {
                return ResourceManager.GetString("Home_NameSearch", resourceCulture);
            }
        }
        
        public static string Home_ImageSearch {
            get {
                return ResourceManager.GetString("Home_ImageSearch", resourceCulture);
            }
        }
        
        public static string Home_Settings {
            get {
                return ResourceManager.GetString("Home_Settings", resourceCulture);
            }
        }
        
        public static string Home_About {
            get {
                return ResourceManager.GetString("Home_About", resourceCulture);
            }
        }
        
        public static string Home_Logout {
            get {
                return ResourceManager.GetString("Home_Logout", resourceCulture);
            }
        }
        
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        public static string About_P1 {
            get {
                return ResourceManager.GetString("About_P1", resourceCulture);
            }
        }
        
        public static string About_P2 {
            get {
                return ResourceManager.GetString("About_P2", resourceCulture);
            }
        }
        
        public static string About_P3 {
            get {
                return ResourceManager.GetString("About_P3", resourceCulture);
            }
        }
        
        public static string About_P4 {
            get {
                return ResourceManager.GetString("About_P4", resourceCulture);
            }
        }
        
        public static string About_Team {
            get {
                return ResourceManager.GetString("About_Team", resourceCulture);
            }
        }
        
        public static string About_Feedback {
            get {
                return ResourceManager.GetString("About_Feedback", resourceCulture);
            }
        }
        
        public static string About_Link {
            get {
                return ResourceManager.GetString("About_Link", resourceCulture);
            }
        }
    }
}
