//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CognitiveLocatorDAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonFaces
    {
        public int IdPersonFaces { get; set; }
        public string IdPerson { get; set; }
        public string URL { get; set; }
        public string FaceId { get; set; }
        public string Height { get; set; }
        public string Width { get; set; }
        public string LeftMargin { get; set; }
        public string RightMargin { get; set; }
        public int PersonIdPerson { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
