//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CognitiveLocatorDAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonFaces
    {
        public int IdPersonFaces { get; set; }
        public int idPerson { get; set; }
        public string URL { get; set; }
        public Nullable<int> FaceId { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> LeftMargin { get; set; }
        public Nullable<double> RightMargin { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
