//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CognitiveLocatorDAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public int IdPersona { get; set; }
        public int IdSituacion { get; set; }
        public string NombreAlias { get; set; }
        public int Edad { get; set; }
        public string Foto { get; set; }
        public string Ubicacion { get; set; }
        public System.Data.Entity.Spatial.DbGeography Coordenadas { get; set; }
        public int IdHospital { get; set; }
        public string Notas { get; set; }
        public string Fuente { get; set; }
        public System.DateTime FechaHoraAgregado { get; set; }
        public System.DateTime FechaHoraActualizacion { get; set; }
        public int IdEstatus { get; set; }
    
        public virtual Hospital Hospital { get; set; }
    }
}
